package config

import (
	"bytes"
	"fmt"
	"net"
	"strconv"

	"github.com/chimerakang/macvz/pkg/network/wireguard"
	"gopkg.in/yaml.v3"
)

// meshMetadataSchema marks the shareable node-metadata document so consumers can
// detect and reject formats they do not understand. It is emitted as the
// document's `schema` field and version-bumped on incompatible changes.
const meshMetadataSchema = "macvz.dev/mesh-node-metadata/v1"

// DefaultPeerKeepalive is the persistentKeepalive (seconds) applied to rendered
// peer entries. A small non-zero value keeps NAT mappings open so a node behind
// NAT stays reachable; it matches the value used in the two-node e2e configs.
const DefaultPeerKeepalive = 25

const meshMetadataHeader = "# macvz mesh node metadata — safe to share; contains NO private key.\n" +
	"# Generated by `macvz-mesh export`. Hand it to other nodes; on each of them run\n" +
	"# `macvz-mesh peer` to turn it into a peer entry for their config.\n"

const meshPeersHeader = "# macvz mesh peers — paste under `mesh:` in each OTHER node's config.\n" +
	"# Rendered by `macvz-mesh peer`. Re-render and re-apply whenever a node's\n" +
	"# public key, endpoint, or Pod CIDR changes (see key rotation in docs).\n"

// MeshNodeMetadata is a node's shareable mesh identity: everything another node
// needs to peer with it, and nothing secret. The private key never appears here
// — only the derived public key — so the document is safe to copy between hosts
// over any channel. It is produced by Config.ExportMeshMetadata on the owning
// node and consumed on the other nodes to render their peer config.
type MeshNodeMetadata struct {
	// Schema identifies the document format; see meshMetadataSchema.
	Schema string `yaml:"schema"`
	// Name is the node's Kubernetes node name, used as the peer comment/name.
	Name string `yaml:"node"`
	// PublicKey is the node's WireGuard public key (base64), derived from its
	// private key. It is the only key material in the document.
	PublicKey string `yaml:"publicKey"`
	// Endpoint is the node's reachable "host:port". Empty for a node behind NAT
	// that initiates connections itself.
	Endpoint string `yaml:"endpoint,omitempty"`
	// Address is the node's mesh address in CIDR form (e.g. "10.99.0.1/32"),
	// routed to it through the tunnel.
	Address string `yaml:"address,omitempty"`
	// PodCIDR is the node's Pod CIDR, routed to it through the tunnel so its Pods
	// are reachable across the mesh.
	PodCIDR string `yaml:"podCIDR"`
	// ListenPort is the UDP port the node's WireGuard interface listens on. It is
	// informational (the endpoint already encodes it) and aids diagnostics.
	ListenPort int `yaml:"listenPort,omitempty"`
}

// ExportMeshMetadata derives this node's shareable mesh identity from its
// config, loading (or, on first run, generating and persisting) the node's
// private key so the operator never copies private keys by hand. Only the
// public key is included in the result.
func (c Config) ExportMeshMetadata() (MeshNodeMetadata, error) {
	if !c.Mesh.Enabled {
		return MeshNodeMetadata{}, fmt.Errorf("mesh is not enabled in config; nothing to export")
	}
	priv, err := wireguard.LoadOrCreateKey(c.Mesh.PrivateKeyFile)
	if err != nil {
		return MeshNodeMetadata{}, err
	}

	port := c.Mesh.ListenPort
	if port == 0 {
		port = DefaultMeshListenPort
	}
	endpoint := ""
	if ip := c.Node.InternalIP; ip != "" {
		endpoint = net.JoinHostPort(ip, strconv.Itoa(port))
	}

	md := MeshNodeMetadata{
		Schema:     meshMetadataSchema,
		Name:       c.NodeName,
		PublicKey:  priv.PublicKey().String(),
		Endpoint:   endpoint,
		Address:    c.Mesh.Address,
		PodCIDR:    c.Node.PodCIDR,
		ListenPort: port,
	}
	if md.PodCIDR == "" {
		return MeshNodeMetadata{}, fmt.Errorf("node.podCIDR is required to export mesh metadata (peers route to it); set it in config")
	}
	if err := md.Validate(); err != nil {
		return MeshNodeMetadata{}, err
	}
	return md, nil
}

// Validate checks the metadata is internally consistent before it is rendered
// into another node's config.
func (m MeshNodeMetadata) Validate() error {
	if m.Name == "" {
		return fmt.Errorf("mesh metadata: node name is required")
	}
	if _, err := wireguard.ParseKey(m.PublicKey); err != nil {
		return fmt.Errorf("mesh metadata for %q: publicKey: %w", m.Name, err)
	}
	if _, _, err := net.ParseCIDR(m.PodCIDR); err != nil {
		return fmt.Errorf("mesh metadata for %q: podCIDR %q is not a CIDR: %w", m.Name, m.PodCIDR, err)
	}
	if m.Address != "" {
		if _, _, err := net.ParseCIDR(m.Address); err != nil {
			return fmt.Errorf("mesh metadata for %q: address %q is not a CIDR: %w", m.Name, m.Address, err)
		}
	}
	if m.Endpoint != "" {
		if _, _, err := net.SplitHostPort(m.Endpoint); err != nil {
			return fmt.Errorf("mesh metadata for %q: endpoint %q is not host:port: %w", m.Name, m.Endpoint, err)
		}
	}
	return nil
}

// PeerConfig converts the metadata into a peer entry for another node's config,
// applying the given persistentKeepalive (seconds).
func (m MeshNodeMetadata) PeerConfig(keepalive int) MeshPeerConfig {
	return MeshPeerConfig{
		Name:                m.Name,
		PublicKey:           m.PublicKey,
		Endpoint:            m.Endpoint,
		PodCIDR:             m.PodCIDR,
		Address:             m.Address,
		PersistentKeepalive: keepalive,
	}
}

// Marshal renders the metadata as a self-describing YAML document with a
// human-readable header. The output is what `macvz-mesh export` writes.
func (m MeshNodeMetadata) Marshal() ([]byte, error) {
	if m.Schema == "" {
		m.Schema = meshMetadataSchema
	}
	var buf bytes.Buffer
	buf.WriteString(meshMetadataHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(m); err != nil {
		return nil, fmt.Errorf("marshal mesh metadata: %w", err)
	}
	_ = enc.Close()
	return buf.Bytes(), nil
}

// ParseMeshNodeMetadata decodes and validates a metadata document produced by
// Marshal (or by `macvz-mesh export`).
func ParseMeshNodeMetadata(data []byte) (MeshNodeMetadata, error) {
	var m MeshNodeMetadata
	if err := yaml.Unmarshal(data, &m); err != nil {
		return MeshNodeMetadata{}, fmt.Errorf("parse mesh metadata: %w", err)
	}
	if m.Schema != "" && m.Schema != meshMetadataSchema {
		return MeshNodeMetadata{}, fmt.Errorf("unsupported mesh metadata schema %q (want %q)", m.Schema, meshMetadataSchema)
	}
	if err := m.Validate(); err != nil {
		return MeshNodeMetadata{}, err
	}
	return m, nil
}

// RenderMeshPeers renders a `peers:` YAML fragment for the given nodes, ready to
// paste under `mesh:` in another node's macvz config. keepalive (seconds) is
// applied to every peer. Peers are emitted in input order.
func RenderMeshPeers(nodes []MeshNodeMetadata, keepalive int) (string, error) {
	peers := make([]MeshPeerConfig, 0, len(nodes))
	for _, n := range nodes {
		if err := n.Validate(); err != nil {
			return "", err
		}
		peers = append(peers, n.PeerConfig(keepalive))
	}
	var buf bytes.Buffer
	buf.WriteString(meshPeersHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(struct {
		Peers []MeshPeerConfig `yaml:"peers"`
	}{Peers: peers}); err != nil {
		return "", fmt.Errorf("render mesh peers: %w", err)
	}
	_ = enc.Close()
	return buf.String(), nil
}

// RenderWireGuardPeers renders standalone wg(8) `[Peer]` blocks for the given
// nodes — the snippet for a hand-managed wg/wg-quick config rather than a macvz
// config. keepalive (seconds) is applied to every peer.
func RenderWireGuardPeers(nodes []MeshNodeMetadata, keepalive int) (string, error) {
	var buf bytes.Buffer
	for i, n := range nodes {
		if err := n.Validate(); err != nil {
			return "", err
		}
		single := MeshConfig{Peers: []MeshPeerConfig{n.PeerConfig(keepalive)}}
		peers, err := single.resolvePeers()
		if err != nil {
			return "", err
		}
		if i > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString(peers[0].ConfigBlock())
	}
	return buf.String(), nil
}
